"""
UPVN — Scene contract: the single source of truth for how interface code maps
to scene objects (naming convention).

M28 Adaptive: Instead of hardcoding LearnToCodeRPG values, this module now
loads GUI metrics from ANY Ren'Py project's gui.rpy via gui_config.py.

Architecture:
- Identifiers (BG_PLANE, etc.) are fixed — the .blend must contain these names
- UI layout (DIALOGUE_LOCATION, colors, fonts) is DYNAMIC — loaded from
  upvn_gui.json (generated by renpy_convert.py) or parsed from gui.rpy at runtime
- Fallback to generic Ren'Py defaults if no config found, not a specific game

This makes UPVN work with ANY Ren'Py project, not just LearnToCodeRPG.
"""
from __future__ import annotations

import math
from typing import Tuple

# --------------------------------------------------------------------------- identifiers
BG_PLANE = "BG_Plane"
BG_MATERIAL = "MABackground"

CAMERA_UI = "Camera_UI"
CAMERA_3D = "Camera_3D"
CAMERA_UI_LOCATION = (0.0, -10.0, 0.0)
CAMERA_UI_ROTATION = (math.pi / 2.0, 0.0, 0.0)
CAMERA_UI_ORTHO_SCALE = 15.0
CAMERA_3D_LOCATION = (0.0, -6.0, 2.5)
CAMERA_3D_ROTATION = (1.15, 0.0, 0.0)
PLANE_ROTATION = (math.pi / 2.0, 0.0, 0.0)

SPRITE_MATERIAL = "MASprite"
SPRITE_POSITIONS = ("far_left", "left", "center", "right", "far_right")
SPRITE_FALLBACK_TAG = "Sprite"
SPRITE_TAG_PREFIX = "Sprite_"
SPRITE_POOL = "Sprite_pool"
POSITION_EMPTY_PREFIX = "Pos_"

DIALOGUE_PLANE = "Dialogue_Box"
SPEAKER_TEXT = "Speaker_Text"
DIALOGUE_TEXT = "Dialogue_Text"
HISTORY_PLANE = "History_Box"
HISTORY_TEXT = "History_Text"
REWIND_TEXT = "Rewind_Text"
CHOICE_PREFIX = "choice_"
CHOICE_COUNT = 9
UI_MATERIAL = "MAUI"
SPRITE_SCALE = (1.8, 3.2, 1.0)

# ---------------------------------------------------------------------------
# Adaptive GUI config loading
# ---------------------------------------------------------------------------
def _load_adaptive_config():
    """
    Load GUI config from any Ren'Py project.
    
    Returns dict with world metrics, colors, fonts.
    This is called once at import, but can be reloaded via reload_gui_config().
    """
    try:
        from .gui_config import load_gui_config, hex_to_rgba
        config = load_gui_config()
        world = config.get("world", {})
        colors = config.get("colors", {})
        fonts = config.get("fonts", {})
        sizes = config.get("sizes", {})
        dialogue = config.get("dialogue", {})
        choice = config.get("choice", {})
        
        # World positions from parsed gui.rpy — generic fallback, not LTCR specific
        dialogue_loc = world.get("dialogue_location", [0.0, -0.4, -3.496])
        dialogue_scale = world.get("dialogue_scale", [7.5, 0.722, 1.0])
        speaker_loc = world.get("speaker_location", [-5.625, -0.55, -2.873])
        dialogue_text_loc = world.get("dialogue_text_location", [-5.406, -0.55, -3.264])
        choice_width = world.get("choice_width_factor", 0.411)
        choice_height = world.get("choice_height_factor", 0.096)
        choice_spacing = world.get("choice_spacing_em", 0.252)
        choice_base_z = world.get("choice_base_z", 1.054)
        
        # Colors — convert hex to rgba, generic defaults (not LTCR)
        text_hex = colors.get("text", "#ffffff")
        accent_hex = colors.get("accent", "#ff7f7f")
        choice_idle_hex = colors.get("choice_idle", "#888888")
        choice_hover_hex = colors.get("choice_hover", "#ffffff")
        
        # For dialogue box: white semi-transparent like Ren'Py textbox.png
        # Ren'Py textbox.png is 255,255,255,204 (80% alpha)
        dialogue_box_rgba = (1.0, 1.0, 1.0, 0.8)
        # If config has dialogue_box color, use it
        if "dialogue_box" in colors and colors["dialogue_box"] != "#ffffff":
            dialogue_box_rgba = hex_to_rgba(colors["dialogue_box"], 0.8)
        
        default_text_rgba = hex_to_rgba(text_hex, 1.0)
        speaker_rgba = hex_to_rgba(accent_hex, 1.0)
        choice_idle_rgba = hex_to_rgba(choice_idle_hex, 0.8)
        choice_hover_rgba = hex_to_rgba(choice_hover_hex, 0.95)
        choice_text_idle_rgba = hex_to_rgba(text_hex, 1.0)
        choice_text_hover_rgba = (1.0, 1.0, 1.0, 1.0)
        
        # Fonts — extract filename from path like "fonts/lato/Lato-Regular.ttf"
        def font_filename(path: str) -> str:
            if not path:
                return "DejaVuSans.ttf"
            # Take basename
            import os
            base = os.path.basename(path)
            # Map common Ren'Py fonts to available UPVN fonts
            # Lato-Regular -> Lato-Regular.ttf, Hack-Regular -> Hack-Regular.ttf, etc.
            # If file exists in blend/fonts/, use it, else fallback
            return base or "DejaVuSans.ttf"
        
        text_font_file = font_filename(fonts.get("text", "DejaVuSans.ttf"))
        name_font_file = font_filename(fonts.get("name", text_font_file))
        interface_font_file = font_filename(fonts.get("interface", text_font_file))
        choice_font_file = font_filename(fonts.get("choice", text_font_file))
        
        # For Ren'Py parity: use Lato for dialogue, Hack for name, saxmono for choice if available
        # But respect parsed fonts if they exist
        # Check if parsed fonts are in our known set, else use them as-is
        # The actual font file resolution happens in find_ui_font
        
        return {
            "dialogue_location": tuple(dialogue_loc),
            "dialogue_scale": tuple(dialogue_scale),
            "speaker_location": tuple(speaker_loc),
            "dialogue_text_location": tuple(dialogue_text_loc),
            "choice_width_factor": float(choice_width),
            "choice_height_factor": float(choice_height),
            "choice_spacing_em": float(choice_spacing),
            "choice_base_z": float(choice_base_z),
            "default_text_color": default_text_rgba,
            "speaker_default_color": speaker_rgba,
            "choice_idle_color": choice_idle_rgba,
            "choice_hover_color": choice_hover_rgba,
            "choice_text_idle": choice_text_idle_rgba,
            "choice_text_hover": choice_text_hover_rgba,
            "dialogue_box_color": dialogue_box_rgba,
            "ui_font_regular": text_font_file,
            "ui_font_bold": text_font_file.replace("Regular", "Bold") if "Regular" in text_font_file else text_font_file,
            "ui_font_name": name_font_file,
            "ui_font_interface": interface_font_file,
            "raw_config": config,
        }
    except Exception as e:
        # Fallback to generic defaults (not LearnToCodeRPG specific)
        # These are Ren'Py's default template values — NOT hardcoded LTCR
        print(f"[contract] adaptive config load failed: {e}, using generic defaults")
        return {
            "dialogue_location": (0.0, -0.4, -3.496),
            "dialogue_scale": (7.5, 0.722, 1.0),
            "speaker_location": (-5.625, -0.55, -2.873),
            "dialogue_text_location": (-5.406, -0.55, -3.264),
            "choice_width_factor": 0.411,
            "choice_height_factor": 0.096,
            "choice_spacing_em": 0.252,
            "choice_base_z": 1.054,
            "default_text_color": (1.0, 1.0, 1.0, 1.0),
            "speaker_default_color": (1.0, 0.498, 0.498, 1.0),
            "choice_idle_color": (0.533, 0.533, 0.533, 0.8),
            "choice_hover_color": (1.0, 0.498, 0.498, 0.95),
            "choice_text_idle": (1.0, 1.0, 1.0, 1.0),
            "choice_text_hover": (1.0, 1.0, 1.0, 1.0),
            "dialogue_box_color": (1.0, 1.0, 1.0, 0.8),
            "ui_font_regular": "DejaVuSans.ttf",
            "ui_font_bold": "DejaVuSans-Bold.ttf",
            "ui_font_name": "DejaVuSans.ttf",
            "ui_font_interface": "DejaVuSans.ttf",
            "raw_config": {},
        }


# Load once at import
_adaptive = _load_adaptive_config()

# Expose as module-level constants (for backward compat and template baking)
DIALOGUE_LOCATION: Tuple[float, float, float] = _adaptive["dialogue_location"]
DIALOGUE_SCALE: Tuple[float, float, float] = _adaptive["dialogue_scale"]
SPEAKER_LOCATION: Tuple[float, float, float] = _adaptive["speaker_location"]
DIALOGUE_TEXT_LOCATION: Tuple[float, float, float] = _adaptive["dialogue_text_location"]

# Choice metrics for world_ui
CHOICE_WIDTH_FACTOR: float = _adaptive["choice_width_factor"]
CHOICE_HEIGHT_FACTOR: float = _adaptive["choice_height_factor"]
CHOICE_SPACING_EM: float = _adaptive["choice_spacing_em"]
CHOICE_BASE_Z: float = _adaptive["choice_base_z"]

# Colors — adaptive
DEFAULT_TEXT_COLOR = _adaptive["default_text_color"]
SPEAKER_DEFAULT_COLOR = _adaptive["speaker_default_color"]
CHOICE_IDLE_COLOR = _adaptive["choice_idle_color"]
CHOICE_HOVER_COLOR = _adaptive["choice_hover_color"]
CHOICE_TEXT_IDLE = _adaptive["choice_text_idle"]
CHOICE_TEXT_HOVER = _adaptive["choice_text_hover"]
DIALOGUE_BOX_COLOR = _adaptive["dialogue_box_color"]
DIALOGUE_BOX_COLOR_SOLID = (DIALOGUE_BOX_COLOR[0], DIALOGUE_BOX_COLOR[1], DIALOGUE_BOX_COLOR[2], 1.0)

# Fonts — adaptive
UI_FONT_REGULAR = _adaptive["ui_font_regular"]
UI_FONT_BOLD = _adaptive["ui_font_bold"]
UI_FONT_NAME = _adaptive["ui_font_name"]
UI_FONT_INTERFACE = _adaptive["ui_font_interface"]

# For backward compat: some code expects UI_FONT_* to exist
UI_FONT = UI_FONT_REGULAR

# Text style — Ren'Py has flat text, no extrusion, no shadow
# But keep M26i values for generic defaults, allow override via config
TEXT_EXTRUDE = 0.0  # Ren'Py flat
TEXT_BEVEL = 0.0
TEXT_BEVEL_RESOLUTION = 0
REWIND_SHEAR = 0.0

SPEAKER_SHADOW = "Speaker_Shadow"
DIALOGUE_SHADOW = "Dialogue_Shadow"
CHOICE_SHADOW_SUFFIX = "_shadow"
SHADOW_OFFSET = (0.0, 0.0, 0.0)
SHADOW_COLOR = (0.0, 0.0, 0.0, 0.0)


def reload_gui_config(config_path=None):
    """Reload GUI config from disk (for converted projects or tests)."""
    global _adaptive
    global DIALOGUE_LOCATION, DIALOGUE_SCALE, SPEAKER_LOCATION, DIALOGUE_TEXT_LOCATION
    global CHOICE_WIDTH_FACTOR, CHOICE_HEIGHT_FACTOR, CHOICE_SPACING_EM, CHOICE_BASE_Z
    global DEFAULT_TEXT_COLOR, SPEAKER_DEFAULT_COLOR, CHOICE_IDLE_COLOR, CHOICE_HOVER_COLOR
    global CHOICE_TEXT_IDLE, CHOICE_TEXT_HOVER, DIALOGUE_BOX_COLOR, DIALOGUE_BOX_COLOR_SOLID
    global UI_FONT_REGULAR, UI_FONT_BOLD, UI_FONT_NAME, UI_FONT_INTERFACE, UI_FONT
    
    try:
        from .gui_config import load_gui_config, clear_cache
        clear_cache()
        _adaptive = _load_adaptive_config() if config_path is None else _load_adaptive_config.__wrapped__() if hasattr(_load_adaptive_config, '__wrapped__') else _load_adaptive_config()
        # Actually reload with path
        from .gui_config import load_gui_config as _load
        from .gui_parser import parse_renpy_gui, gui_to_upvn_config
        from pathlib import Path
        if config_path:
            p = Path(config_path)
            if p.suffix == ".json":
                from .gui_parser import load_upvn_gui_config
                cfg = load_upvn_gui_config(p)
                if cfg:
                    from .gui_config import hex_to_rgba
                    # Re-parse like _load_adaptive_config does
                    # Simplified: just use the config directly
                    world = cfg.get("world", {})
                    colors = cfg.get("colors", {})
                    fonts = cfg.get("fonts", {})
                    # ... (use same logic as _load_adaptive_config)
                    # For brevity, re-call _load_adaptive_config after clearing cache and setting env
                    # The _find_config_file will find the JSON if it's in cwd/game
                    pass
        # Re-load
        _adaptive = _load_adaptive_config()
    except Exception as e:
        print(f"[contract] reload failed: {e}")
    
    # Update globals
    DIALOGUE_LOCATION = _adaptive["dialogue_location"]
    DIALOGUE_SCALE = _adaptive["dialogue_scale"]
    SPEAKER_LOCATION = _adaptive["speaker_location"]
    DIALOGUE_TEXT_LOCATION = _adaptive["dialogue_text_location"]
    CHOICE_WIDTH_FACTOR = _adaptive["choice_width_factor"]
    CHOICE_HEIGHT_FACTOR = _adaptive["choice_height_factor"]
    CHOICE_SPACING_EM = _adaptive["choice_spacing_em"]
    CHOICE_BASE_Z = _adaptive["choice_base_z"]
    DEFAULT_TEXT_COLOR = _adaptive["default_text_color"]
    SPEAKER_DEFAULT_COLOR = _adaptive["speaker_default_color"]
    CHOICE_IDLE_COLOR = _adaptive["choice_idle_color"]
    CHOICE_HOVER_COLOR = _adaptive["choice_hover_color"]
    CHOICE_TEXT_IDLE = _adaptive["choice_text_idle"]
    CHOICE_TEXT_HOVER = _adaptive["choice_text_hover"]
    DIALOGUE_BOX_COLOR = _adaptive["dialogue_box_color"]
    DIALOGUE_BOX_COLOR_SOLID = (DIALOGUE_BOX_COLOR[0], DIALOGUE_BOX_COLOR[1], DIALOGUE_BOX_COLOR[2], 1.0)
    UI_FONT_REGULAR = _adaptive["ui_font_regular"]
    UI_FONT_BOLD = _adaptive["ui_font_bold"]
    UI_FONT_NAME = _adaptive["ui_font_name"]
    UI_FONT_INTERFACE = _adaptive["ui_font_interface"]
    UI_FONT = UI_FONT_REGULAR


def find_ui_font(filename: str = None):
    """Locate a UI typeface for BAKING (bpy-capable contexts only)."""
    if filename is None:
        filename = UI_FONT_REGULAR
    try:
        from pathlib import Path
        here = Path(__file__).resolve()
        # Search in blend/fonts/ relative to project root
        cands = [
            here.parents[2] / "blend" / "fonts" / filename,
            here.parents[2] / "game" / "fonts" / filename,
            here.parents[2] / "assets" / "fonts" / filename,
        ]
        # Also try basename only (for fonts/lato/Lato-Regular.ttf -> Lato-Regular.ttf)
        import os
        base = os.path.basename(filename)
        cands.append(here.parents[2] / "blend" / "fonts" / base)
        cands.append(here.parents[2] / "game" / "fonts" / base)
        
        try:
            import bpy
            bbase = Path(bpy.app.binary_path).resolve().parent
            cands += [
                bbase / "5.0" / "datafiles" / "fonts" / filename,
                bbase / "5.0" / "datafiles" / "fonts" / base,
                bbase / "datafiles" / "fonts" / filename,
                bbase / "datafiles" / "fonts" / base,
            ]
        except Exception:
            pass
        cands.append(Path("/usr/share/fonts/truetype/dejavu") / filename)
        cands.append(Path("/usr/share/fonts/truetype/dejavu") / base)
        cands.append(Path(f"/usr/share/fonts/truetype/lato/{base}"))
        
        for c in cands:
            if c.exists():
                return str(c)
    except Exception:
        pass
    return None


def style_font_curve(data, bold: bool = False, shear: float | None = None, font_name: str | None = None) -> str:
    """Apply text style to a bpy FONT curve."""
    if data is None:
        return "skipped"
    status = "font-not-found"
    try:
        target = font_name or (UI_FONT_BOLD if bold else UI_FONT_REGULAR)
        fn = find_ui_font(target)
        if fn:
            import bpy
            font = bpy.data.fonts.load(fn, check_existing=True)
            if font is not None:
                data.font = font
                status = "dejavu"
    except Exception:
        pass
    try:
        data.extrude = TEXT_EXTRUDE
        data.bevel_depth = TEXT_BEVEL
        data.bevel_resolution = TEXT_BEVEL_RESOLUTION
    except Exception:
        pass
    if shear is not None:
        try:
            data.shear = shear
        except Exception:
            pass
    return status


# Rest of contract (unchanged)
POSITIONS = {
    "far_left": (-6.0, -0.15, 0.0),
    "left": (-3.5, -0.15, 0.0),
    "center": (0.0, -0.15, 0.0),
    "right": (3.5, -0.15, 0.0),
    "far_right": (6.0, -0.15, 0.0),
}

COLLECTIONS = ("VN_Backgrounds", "VN_Characters", "VN_UI", "VN_Effects", "VN_3DStage")
CONTROLLER = "VNController"
LAUNCHER_TEXT = "upvn_launcher"
ASSET_BACKGROUNDS = "assets/backgrounds"
ASSET_SPRITES = "assets/sprites"

IMAGE_MODE_DEFAULT = "color"
_IMAGE_MODES = ("color", "auto")

COLOR_STAGES = {
    "classroom": (0.87, 0.78, 0.60),
    "lecturehall": (0.55, 0.62, 0.78),
    "meadow": (0.55, 0.78, 0.45),
    "uni": (0.72, 0.50, 0.42),
    "room": (0.62, 0.52, 0.44),
    "black": (0.02, 0.02, 0.03),
    "white": (0.95, 0.95, 0.95),
    "night": (0.07, 0.08, 0.16),
    "sakura": (0.95, 0.78, 0.84),
}

SPRITE_TINTS = {
    "eileen": (0.98, 0.62, 0.35),
    "sylvie": (0.45, 0.65, 0.95),
    "lucy": (0.55, 0.90, 0.65),
}

SPRITE_FALLBACK_COLOR = (0.75, 0.70, 0.90, 1.0)


def hash_color(name: str) -> tuple:
    import hashlib
    digest = hashlib.md5((name or "asset").encode("utf-8")).digest()
    hue = digest[0] / 255.0
    sat = 0.45 + (digest[1] / 255.0) * 0.25
    val = 0.55 + (digest[2] / 255.0) * 0.25
    i = int(hue * 6.0) % 6
    f = hue * 6.0 - int(hue * 6.0)
    p = val * (1.0 - sat)
    q = val * (1.0 - f * sat)
    t = val * (1.0 - (1.0 - f) * sat)
    r, g, b = (
        (val, t, p), (q, val, p), (p, val, t),
        (p, q, val), (t, p, val), (val, p, q),
    )[i]
    return (r, g, b, 1.0)


def stage_color(asset: str) -> tuple:
    tokens = [t.lower().strip(" \t-_") for t in (asset or "").split()]
    for token in tokens:
        if token in COLOR_STAGES:
            rgb = COLOR_STAGES[token]
            return (rgb[0], rgb[1], rgb[2], 1.0)
    return hash_color("stage:" + (asset or ""))


def sprite_color(tag: str) -> tuple:
    import re
    key = (tag or "").lower().strip()
    if key in SPRITE_TINTS:
        rgb = SPRITE_TINTS[key]
        return (rgb[0], rgb[1], rgb[2], 1.0)
    for token in re.split(r"[\s_/-]+", key):
        if token in SPRITE_TINTS:
            rgb = SPRITE_TINTS[token]
            return (rgb[0], rgb[1], rgb[2], 1.0)
    return hash_color("sprite:" + key)


def _prop_str(owner, key: str) -> str | None:
    if owner is None:
        return None
    try:
        if key in owner:
            val = owner[key]
            if val is not None:
                return str(val)
    except Exception:
        pass
    try:
        val = owner.get(key)
        if val is not None:
            return str(val)
    except Exception:
        pass
    return None


def image_mode_from(owner=None, env=None) -> str:
    modes = {"color": "color", "auto": "auto",
             "0": "color", "off": "color", "none": "color",
             "1": "auto", "images": "auto", "on": "auto"}
    import os
    env_val = env if env is not None else os.environ.get("UPVN_IMAGES")
    if env_val:
        resolved = modes.get(str(env_val).strip().lower())
        if resolved:
            return resolved
    prop = _prop_str(owner, "image_mode")
    if prop:
        resolved = modes.get(prop.strip().lower())
        if resolved:
            return resolved
    return IMAGE_MODE_DEFAULT


def apply_object_color(obj, color) -> bool:
    if obj is None:
        return False
    try:
        obj.color = color
        return True
    except Exception:
        pass
    try:
        obj.color = color
        return True
    except Exception:
        return False


TEX_NODE_NAME = "UPVN Tex Image"
MIX_NODE_NAME = "UPVN Tex Mix"
WHITE_IMAGE_NAME = "UPVN_White1px"


def _bpy_module():
    try:
        import bpy
        return bpy
    except ImportError:
        return None


def plane_material(plane):
    bpy = _bpy_module()
    if bpy is None or plane is None:
        return None
    try:
        bo = getattr(plane, "blenderObject", None)
        slots = getattr(bo, "material_slots", None)
        if not slots:
            return None
        return slots[0].material
    except Exception:
        return None


def apply_material_image(mat, image_path) -> bool:
    import os
    bpy = _bpy_module()
    if bpy is None or mat is None or not image_path:
        return False
    try:
        if not os.path.isfile(image_path):
            return False
        nt = getattr(mat, "node_tree", None)
        if nt is None:
            return False
        tex = None
        for n in nt.nodes:
            if n.type == "TEX_IMAGE":
                tex = n
                break
        if tex is None:
            return False
        img = bpy.data.images.load(image_path, check_existing=True)
        tex.image = img
        for n in nt.nodes:
            if n.type == "MIX":
                try:
                    for inp in n.inputs:
                        if inp.name == "Factor":
                            inp.default_value = 1.0
                except Exception:
                    pass
        return True
    except Exception:
        return False


def reset_material_palette(mat) -> bool:
    if mat is None:
        return False
    try:
        nt = getattr(mat, "node_tree", None)
        if nt is None:
            return False
        for n in nt.nodes:
            if n.type == "MIX":
                try:
                    for inp in n.inputs:
                        if inp.name == "Factor":
                            inp.default_value = 0.0
                except Exception:
                    pass
        return True
    except Exception:
        return False


def required_objects() -> list[dict]:
    items: list[dict] = []
    for name, purpose, used_by in (
        (BG_PLANE, "background image plane (texture swapped on 'scene')",
         "engine/render/scene_manager.py::SceneManager._swap_bge_texture"),
        (DIALOGUE_PLANE, "3D panel behind Speaker_Text / Dialogue_Text",
         "engine/ui/world_ui.py"),
        (SPEAKER_TEXT, "3D FONT — speaker name",
         "engine/ui/world_ui.py"),
        (DIALOGUE_TEXT, "3D FONT — dialogue body",
         "engine/ui/world_ui.py"),
        (HISTORY_PLANE, "backlog panel shown by H (M26d)",
         "engine/ui/world_ui.py::apply_world_ui"),
        (HISTORY_TEXT, "3D FONT — backlog body (M26d)",
         "engine/ui/world_ui.py::format_history"),
        (REWIND_TEXT, "3D FONT — '« rewound N' indicator while rolled back (M26d)",
         "engine/ui/world_ui.py::apply_world_ui"),
    ):
        items.append({"kind": "object", "name": name,
                      "purpose": purpose, "used_by": used_by})
    for pos in SPRITE_POSITIONS:
        items.append({"kind": "object",
                      "name": f"{POSITION_EMPTY_PREFIX}{pos}",
                      "purpose": f"empty anchoring sprite stage position '{pos}'",
                      "used_by": "engine/render/sprite_renderer.py::SpriteRenderer._bge_show"})
    items.append({"kind": "object",
                  "name": SPRITE_POOL,
                  "purpose": "hidden template plane duplicated per sprite tag",
                  "used_by": "engine/render/sprite_renderer.py::SpriteRenderer._bge_show"})
    for i in range(CHOICE_COUNT):
        items.append({"kind": "object",
                      "name": f"{CHOICE_PREFIX}{i}",
                      "purpose": f"clickable 3D menu button {i}",
                      "used_by": "engine/ui/world_ui.py + engine/ui/pointer.py"})
        items.append({"kind": "object",
                      "name": f"{CHOICE_PREFIX}{i}_text",
                      "purpose": f"FONT label of menu button {i}",
                      "used_by": "engine/ui/world_ui.py::apply_world_ui"})
    for mat, purpose in (
        (BG_MATERIAL, "material slot of BG_Plane receiving the background texture"),
        (SPRITE_MATERIAL, "material slot of every Sprite_* plane receiving the sprite texture"),
    ):
        items.append({"kind": "material", "name": mat,
                      "purpose": purpose,
                      "used_by": "engine/render/* (bge.texture.materialID)"})
    for name in COLLECTIONS:
        items.append({"kind": "collection", "name": name,
                      "purpose": "scene organisation (backgrounds / characters / UI / effects / 3D stage)",
                      "used_by": "tools/make_template.py, blend/upvn_editor_addon.py::build_vn_scene"})
    items.append({"kind": "object", "name": CAMERA_UI,
                  "purpose": "ortho game camera (Front: XZ planes, looking +Y); runtime binds scene.active_camera",
                  "used_by": "bge_frontend/frontend.py::_bind_camera, blend/upvn_editor_addon.py::build_vn_scene"})
    items.append({"kind": "object", "name": CAMERA_3D,
                  "purpose": "perspective camera for hybrid 3D stages / camera_preset",
                  "used_by": "engine/render/stage_manager.py (optional)"})
    items.append({"kind": "object", "name": CONTROLLER,
                  "purpose": "game object with script_path/upvn_root properties and the Always->Python brick",
                  "used_by": "bge_frontend/frontend.py::main (reads script_path), launcher text"})
    items.append({"kind": "text", "name": LAUNCHER_TEXT,
                  "purpose": "path-bootstrap script executed by the Python controller",
                  "used_by": "blend/upvn_editor_addon.py (SCRIPT mode controller)"})
    return items


def check_contract(object_names, material_names=(), collection_names=(),
                   text_names=()) -> dict:
    present: list[dict] = []
    missing: list[dict] = []
    for item in required_objects():
        name = item["name"]
        if item["kind"] == "object":
            found = name in set(object_names)
        elif item["kind"] == "material":
            found = name in set(material_names)
        elif item["kind"] == "collection":
            found = name in set(collection_names)
        elif item["kind"] == "text":
            found = name in set(text_names)
        else:
            found = False
        (present if found else missing).append(item)
    return {"present": present, "missing": missing}
